---
title: "load_regions"
author: "Ben Best"
date: "9/2/2021"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Create Regions

Sources:
* [Marine Regions · United States Exclusive Economic Zone (EEZ)](https://www.marineregions.org/gazetteer.php?p=details&id=8456)
* [Marine Regions · Gulf of Saint Lawrence (IHO Sea Area)](https://www.marineregions.org/gazetteer.php?p=details&id=4290)

```{r}
librarian::shelf(
  dplyr, glue, here, lwgeom, purrr, sf, tibble)

usa_url <- "https://geo.vliz.be/geoserver/wfs?request=getfeature&service=wfs&version=1.1.0&typename=MarineRegions:eez&outputformat=json&filter=%3CPropertyIsEqualTo%3E%3CPropertyName%3Emrgid%3C%2FPropertyName%3E%3CLiteral%3E8456%3C%2FLiteral%3E%3C%2FPropertyIsEqualTo%3E"

can_gsl_url <- "https://geo.vliz.be/geoserver/wfs?request=getfeature&service=wfs&version=1.1.0&typename=MarineRegions:iho&outputformat=json&filter=%3CPropertyIsEqualTo%3E%3CPropertyName%3Eid%3C%2FPropertyName%3E%3CLiteral%3E24%3C%2FLiteral%3E%3C%2FPropertyIsEqualTo%3E"

usa_json     <- here("data/usa_parts.geojson")
fl_json      <- here("data/fl_line.geojson") # manually created in QGIS
rgns_json    <- here("data/ws-rgns.geojson")

if (!file.exists(rgns_json)){
  
  if (!file.exists(usa_json)){
    usa <- sf::read_sf(usa_url)
    
    usa_parts <- st_cast(usa, "POLYGON") %>% 
      rownames_to_column("rowid") %>% 
      select(rowid, geometry) %>% 
      st_as_sf(sf_column_name = "geometry")
    
    write_sf(usa_parts, usa_json)
  }
  
  usa_parts <- read_sf(usa_json)
  fl_ln     <- read_sf(fl_json)

  # split
  rgns <- lwgeom::st_split(usa_parts, fl_ln) %>% # SLOW: 15 minutes
    st_collection_extract(c("POLYGON"))
  
  # add ctr_lon to differentiate
  rgns <- rgns %>% 
    mutate(
      pt_ctr = st_centroid(geometry),
      ctr_lon = map_dbl(pt_ctr, ~ st_coordinates(.x)[1]),
      ctr_lat = map_dbl(pt_ctr, ~ st_coordinates(.x)[2])) %>% 
    select(-pt_ctr) %>% 
    arrange(rowid, ctr_lon) %>% 
    rownames_to_column("rowid2")
  
  rgns <- rgns %>% 
    filter(ctr_lon < -80.5) %>% 
    arrange(ctr_lon) %>% 
    mutate(
      region = c("USA_West", "USA_GoMex")) %>% 
    select(region, geometry) %>% 
    rbind(
      # East
      rgns %>% 
        # st_drop_geometry() %>% 
        filter(ctr_lon > -80.5) %>% 
        st_union()  %>% 
        st_as_sf() %>% 
        mutate(
          region = "USA_East") %>% 
        rename(geometry = x))

  # + Canada's Gulf of St Lawrence
  # rgns <- read_sf(rgns_json)
  can_gsl <- read_sf(can_gsl_url) %>%
    mutate(
      region = "CAN_GoStLawrence") %>% 
    select(region)
  rgns <- rbind(
    rgns %>% filter(region!="CAN_GoStLawrence"),
    can_gsl)
  
  write_sf(rgns, rgns_json, delete_dsn=T)
}
rgns <- read_sf(rgns_json)
```

## Upload to BigQuery DB

```{r}
source(here::here("scripts/db.R"))
shelf(stringr)

# vars
bq_tbl_rgns <- "benioff-ocean-initiative.whalesafe_v4.regions"
update_rgns <- F


bq_ds_rgns  <- str_replace(bq_tbl_rgns, "(.*?)\\.(.*?)\\.(.*?)", "\\1.\\2")
if (!bq_dataset_exists(bq_ds_rgns))
  bq_dataset_create(bq_ds_rgns)

if (!bq_table_exists(bq_tbl_rgns) | update_rgns){
  
  rgns_wkt <- rgns %>% 
  mutate(
    wkt = st_as_text(geometry)) %>% 
    st_drop_geometry()
  
  if (!bq_table_exists(bq_tbl_rgns)){
    bq_table_delete(bq_tbl_rgns)
  }
    
  bq_rgns <- bq_table_create(
    bq_tbl_rgns,
    rgns_wkt,
    friendly_name = "WhaleSafe regions",
    description   = "Created by:
        https://github.com/BenioffOceanInitiative/ws-sql/blob/main/load_regions.Rmd",
    labels = list(category = "spatial"))
  
  bq_table_upload(bq_tbl_rgns, rgns_wkt)
  
  bq_dataset_query(
    bq_ds_rgns,
    glue(
      "ALTER TABLE {bq_tbl_rgns} ADD COLUMN IF NOT EXISTS geog GEOGRAPHY;
       UPDATE {bq_tbl_rgns} SET geog = ST_GEOGFROMTEXT(wkt) WHERE TRUE;
       ALTER TABLE {bq_tbl_rgns} DROP COLUMN IF EXISTS wkt"))
  # NOTE: UPDATE requires WHERE TRUE; try in console editor to see errors
}

rgns_bq <- bq_table_download(bq_tbl_rgns) %>% 
  st_as_sf(wkt = "geog", crs = 4326)
```


